language: python            # this works for Linux but is an error on macOS or Windows

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      env: PYAPP=python

    - name: "PyPy 3.5 on Xenial Linux"
      python: pypy3.5       
      dist: xenial          
      env: PYAPP=python

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYAPP=python3

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PYAPP=python

    - name: "PyPy 3.7.x (PyPy 7.1) on Windows"
      os: windows           
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install pypy3
        - ls -l /c/ProgramData/chocolatey/lib/pypy3
        - ls -l /c/ProgramData/chocolatey/lib/pypy3/tools
        - ls -l /c/ProgramData/chocolatey/lib/pypy3/tools/pypy3.6-v7.1.0-win32
        - curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
        - pypy3 get-pip.py

      env:
        - PATH=/c/ProgramData/chocolatey/lib/pypy3/tools/pypy3.6-v7.1.0-win32:$PATH
        - PYAPP=pypy3
      
install:
- |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
       $PYAPP -m pip install -U pip   
    else
       pip3 install --upgrade pip 
    fi   
- pip3 install numpy pytest

# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
- $PYAPP -m pytest
