language: python            # this works for Linux but is an error on macOS or Windows

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      env: PYAPP=python

    - name: "PyPy 3.5 on Xenial Linux"
      python: pypy3.5       
      dist: xenial          
      env: PYAPP=python

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: PYAPP=python3

    - name: "PyPy on macOS"
      os: osx
      python: "pypy3.5"
      env: PYAPP=pypy3 TRAVIS_PYTHON_VERSION="pypy3"
      before_install:
        - curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
        - which pypy || which pypy3
        - pypy3 get-pip.py
        - pypy3 -m pip install numpy

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PYAPP=python

    #using pypy on windows with pytest appears to be somewhat hard (commented out)
    - name: "PyPy 3.7.x (PyPy 7.1) on Windows"
      os: windows           
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install pypy3
        - ls -l /c/ProgramData/chocolatey/lib/pypy3/tools/pypy3.6-v7.1.0-win32/libs
        - ls -l /c/ProgramData/chocolatey/lib/pypy3/tools/pypy3.6-v7.1.0-win32/site-packages
        #http://pypy.org/download.html#installing-numpy
        #http://doc.pypy.org/en/latest/faq.html#should-i-install-numpy-or-numpypy
        - curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
        - pypy3 get-pip.py
        - pypy3 -m pip install numpy

      env:
        - PATH=/c/ProgramData/chocolatey/lib/pypy3/tools/pypy3.6-v7.1.0-win32/bin:$PATH
        - PYAPP=pypy3
      
install:
- $PYAPP -m pip install -U pip   
- $PYAPP -m pip install pytest
- $PYAPP -m pip install numpy

script:
- $PYAPP -m pytest || $PYAPP fallback_numpy_normal.py
